version: "3.9"
services:
  mongodb:
    image: mongo:6.0.1
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - "./volumes/mongodb/data:/data"
  app:
    image: devdimas/cp-simple-ecommerce:base
    restart: unless-stopped
    environment:
      - MONGODB_HOST=154.26.131.99
      - MONGODB_PORT=31017
      - MONGODB_DATABASE=bootcamp-b5-kelompok3
      - MONGODB_USERNAME=kelompok3
      - MONGODB_PASSWORD=MSIBB5123
      - JWT_SECRET_KEY=z6mXSZbFwBklvuLGyQJdfxUJGdun1I

    ports:
      - 3000:3000
