name: Feature checking

on:
  push:
    branches:
      - "**"
      - "!master"
      - "!main"
      - "!staging"

env:
  MONGODB_HOST: localhost
  MONGODB_PORT: 27017
  MONGODB_DATABASE: e-commerce
  MONGODB_USERNAME:
  MONGODB_PASSWORD:
  JWT_SECRET_KEY: Wq9FnbgaEg3a0sGECGIY92dqektQl1

jobs:
  checking-feature:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup nodejs v18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: install dependencies
        run: npm install

      - name: run application
        run: npm start&

      - name: test if app is working
        run: until curl -v http://localhost:3000  > /dev/null; do sleep 1; done
  test-feature:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: checking-feature
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "6.0"
          mongodb-username: root
          mongodb-password: root
          mongodb-db: github-action-db

      - name: setup nodejs v18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: install dependencies
        run: npm install

      - name: test features
        run: npm run test
